-- Customer codes must be generated by the database, not by a client-side row count
-- (two concurrent creations could otherwise produce the same code).
CREATE OR REPLACE FUNCTION public.v2_set_customer_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.customer_code IS NULL OR btrim(NEW.customer_code) = '' THEN
    NEW.customer_code := public.v2_next_reference('customer:' || NEW.organization_id::text, 'CUS', 6);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS v2_customers_set_code ON public.v2_customers;
CREATE TRIGGER v2_customers_set_code
  BEFORE INSERT ON public.v2_customers
  FOR EACH ROW EXECUTE FUNCTION public.v2_set_customer_code();

REVOKE ALL ON FUNCTION public.v2_set_customer_code() FROM PUBLIC, anon, authenticated;