INSERT INTO public.v2_compliance_programs
  (code, name_fr, name_en, description_fr, description_en, country, product_applicability, version,
   effective_date, is_active, source_reference, disclaimer_fr, disclaimer_en, managed_by, sort_order)
VALUES (
 'BJ_FOOD_HYGIENE_V1',
 'Hygiène et sécurité sanitaire des aliments — Bénin (pilote)',
 'Food hygiene and safety — Benin (pilot)',
 'Auto-évaluation structurée des bonnes pratiques d''hygiène et de fabrication pour les unités de transformation agroalimentaire au Bénin. Sert à préparer un audit ou une inspection.',
 'Structured self-assessment of good hygiene and manufacturing practices for agro-processing units in Benin. Used to prepare for an audit or inspection.',
 'BJ', 'Transformation agroalimentaire / Agro-processing', '1.0', CURRENT_DATE, true,
 'Bonnes pratiques d''hygiène (BPH) et bonnes pratiques de fabrication (BPF) — référentiel pilote AgriGrid',
 'Ce référentiel est un outil de préparation interne. Il ne constitue ni une certification, ni une validation officielle, ni un avis réglementaire. Seules les autorités compétentes et les organismes accrédités peuvent délivrer une certification.',
 'This framework is an internal preparation tool. It is not a certification, an official validation or a regulatory opinion. Only competent authorities and accredited bodies can issue a certification.',
 'agrigrid', 1);

WITH p AS (SELECT id FROM public.v2_compliance_programs WHERE code = 'BJ_FOOD_HYGIENE_V1')
INSERT INTO public.v2_compliance_requirements
 (program_id, code, title_fr, title_en, description_fr, description_en, category, severity,
  requirement_type, scope, guidance_fr, guidance_en, evidence_expected_fr, evidence_expected_en,
  system_evidence_rule, sort_order)
SELECT p.id, x.code, x.tfr, x.ten, x.dfr, x.den, x.cat::v2_compliance_category, x.sev::v2_compliance_severity,
       x.rtype::v2_requirement_type, x.scope::v2_compliance_scope, x.gfr, x.gen, x.efr, x.een, x.sysrule, x.ord
FROM p, (VALUES
 ('BJ-PRE-01','Locaux séparés des zones de contamination','Premises separated from contamination sources','Les locaux de production sont isolés des sources de contamination (latrines, déchets, élevage, poussière).','Production premises are isolated from contamination sources (latrines, waste, livestock, dust).','premises','critical','yes_no','facility','Vérifier les distances, les murs et les ouvertures.','Check distances, walls and openings.','Photos des locaux et du plan de site.','Photos of premises and site layout.',NULL,10),
 ('BJ-PRE-02','Sols, murs et plafonds lavables','Floors, walls and ceilings washable','Les surfaces des zones de production sont lisses, non poreuses et faciles à nettoyer.','Production area surfaces are smooth, non-porous and easy to clean.','premises','high','yes_no','facility','Pas de fissures ni de revêtements absorbants.','No cracks or absorbent coatings.','Photos des surfaces.','Photos of surfaces.',NULL,20),
 ('BJ-PRE-03','Séparation des flux propres et sales','Separation of clean and dirty flows','Le circuit des matières premières ne croise pas celui des déchets ni des produits finis.','Raw material flow does not cross waste or finished product flows.','premises','high','yes_no','facility','Décrire le sens de circulation.','Describe the flow direction.','Plan de circulation ou schéma.','Flow plan or diagram.',NULL,30),
 ('BJ-HYG-01','Points de lavage des mains opérationnels','Operational handwashing points','Des postes de lavage des mains avec eau, savon et séchage sont disponibles à l''entrée des zones de production.','Handwashing stations with water, soap and drying are available at production area entrances.','hygiene','critical','photo_required','facility','Vérifier la présence effective de savon et d''eau.','Check that soap and water are actually present.','Photo du poste de lavage.','Photo of the washing station.',NULL,40),
 ('BJ-HYG-02','Règles d''hygiène affichées','Hygiene rules displayed','Les consignes d''hygiène sont affichées en français et compréhensibles par tout le personnel.','Hygiene instructions are displayed in French and understandable to all staff.','hygiene','medium','photo_required','facility','Affichage visible dans les zones de travail.','Visible display in work areas.','Photo de l''affichage.','Photo of the display.',NULL,50),
 ('BJ-PER-01','Tenue de travail propre et dédiée','Clean dedicated work clothing','Le personnel dispose de blouses, coiffes et chaussures dédiées à la production.','Staff have dedicated coats, hairnets and footwear for production.','personnel','high','yes_no','facility','Prévoir le nettoyage régulier des tenues.','Plan regular cleaning of workwear.','Photo du personnel en tenue.','Photo of staff in workwear.',NULL,60),
 ('BJ-PER-02','Aptitude médicale du personnel','Staff medical fitness','Les personnes manipulant les denrées disposent d''un certificat d''aptitude à jour.','Food handlers hold a valid fitness certificate.','personnel','critical','document_required','organization','Renouveler selon la périodicité exigée localement.','Renew according to the locally required frequency.','Certificats médicaux.','Medical certificates.',NULL,70),
 ('BJ-PER-03','Formation à l''hygiène enregistrée','Recorded hygiene training','Le personnel a suivi une formation à l''hygiène et la formation est enregistrée.','Staff have received hygiene training and the training is recorded.','personnel','medium','document_required','organization','Conserver la liste des participants et la date.','Keep the attendance list and date.','Fiche de formation signée.','Signed training record.',NULL,80),
 ('BJ-EQU-01','Équipements en matériaux aptes au contact alimentaire','Food-grade equipment materials','Les équipements en contact avec les produits sont en matériaux aptes au contact alimentaire.','Product-contact equipment is made of food-grade materials.','equipment','critical','yes_no','facility','Éviter le bois brut et les métaux corrodés.','Avoid raw wood and corroded metals.','Photos des équipements.','Photos of equipment.',NULL,90),
 ('BJ-EQU-02','Maintenance et étalonnage des équipements','Equipment maintenance and calibration','Les équipements de mesure (balances, thermomètres) sont contrôlés régulièrement.','Measuring equipment (scales, thermometers) is checked regularly.','equipment','medium','document_required','facility','Tenir un registre de maintenance.','Keep a maintenance register.','Registre ou attestation d''étalonnage.','Register or calibration certificate.',NULL,100),
 ('BJ-RAW-01','Réception des matières premières enregistrée','Raw material receipts recorded','Chaque réception de matière première est enregistrée avec le fournisseur et la quantité.','Every raw material receipt is recorded with supplier and quantity.','raw_materials','critical','confirmation','organization','Généré automatiquement à partir des réceptions AgriGrid.','Automatically derived from AgriGrid goods receipts.','Réceptions enregistrées dans AgriGrid.','Goods receipts recorded in AgriGrid.','SYS_RAW_MATERIAL_RECEIPTS',110),
 ('BJ-RAW-02','Contrôle qualité à réception','Quality check on receipt','Un contrôle visuel ou analytique est effectué et tracé à chaque réception.','A visual or analytical check is performed and recorded on each receipt.','raw_materials','high','yes_no','organization','Consigner acceptation, réserve ou refus.','Record acceptance, reservation or rejection.','Résultat qualité des réceptions.','Quality result of receipts.',NULL,120),
 ('BJ-WAT-01','Potabilité de l''eau utilisée','Potability of water used','L''eau en contact avec les produits est potable et analysée périodiquement.','Water in contact with products is potable and periodically tested.','water','critical','document_required','facility','Analyse en laboratoire recommandée au moins une fois par an.','Laboratory analysis recommended at least once a year.','Bulletin d''analyse d''eau.','Water analysis report.',NULL,130),
 ('BJ-CLE-01','Plan de nettoyage et de désinfection','Cleaning and disinfection plan','Un plan de nettoyage documenté précise les zones, la fréquence et les produits utilisés.','A documented cleaning plan specifies areas, frequency and products used.','cleaning','high','document_required','facility','Associer une fiche de suivi signée.','Attach a signed follow-up sheet.','Plan de nettoyage et fiches de suivi.','Cleaning plan and follow-up sheets.',NULL,140),
 ('BJ-CLE-02','Produits de nettoyage stockés séparément','Cleaning products stored separately','Les produits chimiques sont stockés hors des zones de production et identifiés.','Chemicals are stored outside production areas and labelled.','cleaning','high','photo_required','facility','Local ou armoire fermée.','Locked room or cabinet.','Photo du stockage.','Photo of the storage.',NULL,150),
 ('BJ-PES-01','Dispositif de lutte contre les nuisibles','Pest control arrangement','Un dispositif de prévention et de suivi des nuisibles est en place.','A pest prevention and monitoring arrangement is in place.','pest_control','high','yes_no','facility','Pièges numérotés et plan de localisation.','Numbered traps and location plan.','Plan de piégeage ou contrat prestataire.','Trapping plan or service contract.',NULL,160),
 ('BJ-WAS-01','Gestion et évacuation des déchets','Waste management and disposal','Les déchets sont collectés dans des contenants fermés et évacués régulièrement.','Waste is collected in closed containers and removed regularly.','waste','medium','yes_no','facility','Éviter tout stockage prolongé à proximité de la production.','Avoid prolonged storage near production.','Photo de la zone déchets.','Photo of the waste area.',NULL,170),
 ('BJ-STO-01','Stockage des produits finis maîtrisé','Controlled finished product storage','Les produits finis sont stockés à l''abri, surélevés et protégés de l''humidité.','Finished products are stored sheltered, raised and protected from moisture.','storage','high','photo_required','facility','Palettes ou étagères, pas de contact au sol.','Pallets or shelves, no floor contact.','Photo du magasin.','Photo of the store.',NULL,180),
 ('BJ-STO-02','Conditions de température suivies','Temperature conditions monitored','Lorsque le produit l''exige, la température de stockage est suivie et enregistrée.','Where the product requires it, storage temperature is monitored and recorded.','storage','medium','yes_no','facility','Non applicable pour les produits stables à température ambiante.','Not applicable for ambient-stable products.','Relevés de température.','Temperature records.',NULL,190),
 ('BJ-TRA-01','Lots de produits finis identifiables','Finished lots identifiable','Chaque lot de produit fini porte une référence unique.','Each finished product lot carries a unique reference.','traceability','critical','confirmation','organization','Généré automatiquement à partir des lots AgriGrid.','Automatically derived from AgriGrid finished lots.','Lots enregistrés dans AgriGrid.','Lots recorded in AgriGrid.','SYS_FINISHED_LOT_IDENTIFIABLE',200),
 ('BJ-TRA-02','Traçabilité amont jusqu''au fournisseur','Upstream traceability to supplier','Il est possible de remonter d''un lot de produit fini jusqu''aux fournisseurs de matière première.','It is possible to trace a finished lot back to raw material suppliers.','traceability','critical','confirmation','organization','Généré automatiquement à partir de la traçabilité AgriGrid.','Automatically derived from AgriGrid traceability.','Chaîne de traçabilité AgriGrid.','AgriGrid traceability chain.','SYS_TRACE_FG_TO_SUPPLIER',210),
 ('BJ-TRA-03','Enregistrements de production entrées/sorties','Production input/output records','Chaque production enregistre les matières consommées et les quantités produites.','Each production run records the materials consumed and quantities produced.','traceability','high','confirmation','organization','Généré automatiquement à partir des productions AgriGrid.','Automatically derived from AgriGrid production batches.','Fiches de production AgriGrid.','AgriGrid production records.','SYS_PRODUCTION_IO_RECORDS',220),
 ('BJ-LAB-01','Étiquetage conforme des produits','Compliant product labelling','L''étiquette mentionne la dénomination, le lot, la date de durabilité, le poids et le fabricant.','The label states the name, lot, durability date, weight and manufacturer.','labeling','critical','photo_required','organization','Vérifier la lisibilité et la langue.','Check legibility and language.','Photo de l''étiquette.','Photo of the label.',NULL,230),
 ('BJ-DOC-01','Enregistrement légal de l''entreprise','Legal business registration','L''entreprise dispose de ses documents d''existence légale à jour.','The business holds up-to-date legal existence documents.','documentation','critical','document_required','organization','Conserver la version en cours de validité.','Keep the currently valid version.','Registre du commerce, IFU.','Business registry, tax ID.',NULL,240),
 ('BJ-DOC-02','Procédures écrites disponibles','Written procedures available','Les procédures clés de production et d''hygiène sont écrites et accessibles au personnel.','Key production and hygiene procedures are written and accessible to staff.','documentation','medium','document_required','organization','Une page par procédure suffit pour démarrer.','One page per procedure is enough to start.','Procédures signées.','Signed procedures.',NULL,250),
 ('BJ-QUA-01','Analyses laboratoire du produit fini','Finished product laboratory analysis','Des analyses microbiologiques ou physico-chimiques récentes sont disponibles.','Recent microbiological or physico-chemical analyses are available.','quality_control','high','document_required','organization','Renouveler selon la fréquence définie en interne.','Renew at the internally defined frequency.','Bulletin d''analyse.','Analysis report.',NULL,260),
 ('BJ-QUA-02','Gestion des réclamations et des retraits','Complaint and recall handling','Une procédure de réclamation client et de retrait/rappel de lot existe.','A customer complaint and lot withdrawal/recall procedure exists.','quality_control','high','document_required','organization','Indiquer le responsable et les délais.','State the responsible person and deadlines.','Procédure de rappel.','Recall procedure.',NULL,270)
) AS x(code,tfr,ten,dfr,den,cat,sev,rtype,scope,gfr,gen,efr,een,sysrule,ord);